from __future__ import annotations

from ._b_series_evolution_shared import *

B_SERIES_EVOLUTION_ROOT = Path("artifacts/b_series/evolution")
B1_CAPACITY_ATTEMPTS: tuple[str, ...] = (
    B1_CAPACITY_H48_POLICY_NAME,
    B1_CAPACITY_H64_POLICY_NAME,
)
B1_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B1_CAPACITY_ATTEMPTS,
    B1_THREAT_GUARD_POLICY_NAME,
)
B2_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B2_TEMPORAL_THREAT_H48_POLICY_NAME,
    B2_TEMPORAL_THREAT_H56_POLICY_NAME,
    B2_TEMPORAL_THREAT_H64_POLICY_NAME,
)
B3_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B3_CONTACT_MEMORY_H48_POLICY_NAME,
    B3_CONTACT_MEMORY_STRICT_H48_POLICY_NAME,
    B3_CONTACT_MEMORY_H56_POLICY_NAME,
    B3_RECURRENT_GUARD_H48_POLICY_NAME,
)
B4_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B4_RECOVERY_BALANCE_H48_POLICY_NAME,
    B4_PREDATOR_EXIT_MEMORY_H48_POLICY_NAME,
    B4_RECOVERY_BALANCE_H56_POLICY_NAME,
)
B4_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B4_FIXED_EVOLUTION_ATTEMPTS,
    B4_GENETIC_RECOVERY_H48_POLICY_NAME,
)
B5_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B5_HOMEOSTATIC_ARBITER_H48_POLICY_NAME,
    B5_CIRCADIAN_RECOVERY_H48_POLICY_NAME,
    B5_HOMEOSTATIC_ARBITER_H56_POLICY_NAME,
)
B5_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B5_FIXED_EVOLUTION_ATTEMPTS,
    B5_GENETIC_HOMEOSTASIS_H48_POLICY_NAME,
)
B6_RISK_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B6_RISK_FORAGE_ARBITER_H48_POLICY_NAME,
    B6_CORRIDOR_SURVIVAL_GUARD_H48_POLICY_NAME,
    B6_THREAT_PRIORITY_MEMORY_H48_POLICY_NAME,
    B6_RISK_CORRIDOR_H56_POLICY_NAME,
)
B6_RECURRENT_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B6_RECURRENT_CONTEXT_H48_POLICY_NAME,
    B6_RECURRENT_THREAT_HOMEOSTASIS_H48_POLICY_NAME,
    B6_RECURRENT_CORRIDOR_GUARD_H48_POLICY_NAME,
    B6_RECURRENT_CONTEXT_H56_POLICY_NAME,
)
B6_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B6_RISK_FIXED_EVOLUTION_ATTEMPTS,
    *B6_RECURRENT_FIXED_EVOLUTION_ATTEMPTS,
)
B6_RISK_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B6_RISK_FIXED_EVOLUTION_ATTEMPTS,
    B6_GENETIC_RISK_CORRIDOR_H48_POLICY_NAME,
)
B6_RECURRENT_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B6_RECURRENT_FIXED_EVOLUTION_ATTEMPTS,
    B6_GENETIC_RECURRENT_MEMORY_H48_POLICY_NAME,
)
B6_FUSION_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B6_FUSED_RISK_RECURRENT_H48_POLICY_NAME,
)
B7_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B7_AFFORDANCE_BUDGET_H48_POLICY_NAME,
    B7_ENERGY_BUDGET_CORRIDOR_H48_POLICY_NAME,
    B7_RECURRENT_AFFORDANCE_H48_POLICY_NAME,
    B7_AFFORDANCE_BUDGET_H56_POLICY_NAME,
)
B7_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B7_FIXED_EVOLUTION_ATTEMPTS,
    B7_GENETIC_AFFORDANCE_BUDGET_H48_POLICY_NAME,
)
B8_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B8_SPATIAL_AFFORDANCE_MAP_H48_POLICY_NAME,
    B8_RETURN_VECTOR_H48_POLICY_NAME,
    B8_CORRIDOR_PLACE_MEMORY_H48_POLICY_NAME,
    B8_SPATIAL_AFFORDANCE_MAP_H56_POLICY_NAME,
)
B8_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B8_FIXED_EVOLUTION_ATTEMPTS,
    B8_GENETIC_SPATIAL_AFFORDANCE_H48_POLICY_NAME,
)
B9_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B9_WAYPOINT_PLANNER_H48_POLICY_NAME,
    B9_PATH_INTEGRATION_H48_POLICY_NAME,
    B9_ROUTE_MEMORY_H48_POLICY_NAME,
    B9_WAYPOINT_PLANNER_H56_POLICY_NAME,
)
B9_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B9_FIXED_EVOLUTION_ATTEMPTS,
    B9_GENETIC_WAYPOINT_PLANNER_H48_POLICY_NAME,
)
B10_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B10_PROSPECTIVE_REPLAY_H48_POLICY_NAME,
    B10_VALUE_ROUTE_EVALUATOR_H48_POLICY_NAME,
    B10_REPLAY_PLANNER_H48_POLICY_NAME,
    B10_PROSPECTIVE_REPLAY_H56_POLICY_NAME,
)
B10_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B10_FIXED_EVOLUTION_ATTEMPTS,
    B10_GENETIC_REPLAY_PLANNER_H48_POLICY_NAME,
)
B11_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B11_CONFIDENCE_ARBITER_H48_POLICY_NAME,
    B11_UNCERTAINTY_GATE_H48_POLICY_NAME,
    B11_NEUROMODULATED_REPLAY_H48_POLICY_NAME,
    B11_CONFIDENCE_ARBITER_H56_POLICY_NAME,
)
B11_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B11_FIXED_EVOLUTION_ATTEMPTS,
    B11_GENETIC_CONFIDENCE_GATE_H48_POLICY_NAME,
)
B12_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B12_PREDICTIVE_ATTENTION_H48_POLICY_NAME,
    B12_ACTIVE_INFERENCE_GATE_H48_POLICY_NAME,
    B12_AFFORDANCE_ATTENTION_H48_POLICY_NAME,
    B12_PREDICTIVE_ATTENTION_H56_POLICY_NAME,
)
B12_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B12_FIXED_EVOLUTION_ATTEMPTS,
    B12_GENETIC_ATTENTION_GATE_H48_POLICY_NAME,
)
B13_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B13_LOCAL_AFFORDANCE_SEARCH_H48_POLICY_NAME,
    B13_COUNTERFACTUAL_ROUTE_H48_POLICY_NAME,
    B13_AFFORDANCE_SAMPLER_H48_POLICY_NAME,
    B13_LOCAL_AFFORDANCE_SEARCH_H56_POLICY_NAME,
)
B13_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B13_FIXED_EVOLUTION_ATTEMPTS,
    B13_GENETIC_LOCAL_SEARCH_H48_POLICY_NAME,
)
B14_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B14_AFFORDANCE_UNCERTAINTY_H48_POLICY_NAME,
    B14_RISK_CALIBRATED_SEARCH_H48_POLICY_NAME,
    B14_CONFIDENCE_WEIGHTED_ROUTE_H48_POLICY_NAME,
    B14_AFFORDANCE_UNCERTAINTY_H56_POLICY_NAME,
)
B14_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B14_FIXED_EVOLUTION_ATTEMPTS,
    B14_GENETIC_UNCERTAINTY_SEARCH_H48_POLICY_NAME,
)
B15_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B15_OPTION_CRITIC_H48_POLICY_NAME,
    B15_PERSISTENCE_GATE_H48_POLICY_NAME,
    B15_VALUE_GATED_OPTION_H48_POLICY_NAME,
    B15_OPTION_CRITIC_H56_POLICY_NAME,
)
B15_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B15_FIXED_EVOLUTION_ATTEMPTS,
    B15_GENETIC_OPTION_CRITIC_H48_POLICY_NAME,
)
B16_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B16_OPTION_ENSEMBLE_H48_POLICY_NAME,
    B16_COMPETING_OPTIONS_H48_POLICY_NAME,
    B16_ACTION_SET_VOTER_H48_POLICY_NAME,
    B16_OPTION_ENSEMBLE_H56_POLICY_NAME,
)
B16_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B16_FIXED_EVOLUTION_ATTEMPTS,
    B16_GENETIC_OPTION_ENSEMBLE_H48_POLICY_NAME,
)
B17_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B17_NEUROMODULATED_ENSEMBLE_H48_POLICY_NAME,
    B17_AROUSAL_GATED_OPTIONS_H48_POLICY_NAME,
    B17_HOMEOSTATIC_MODULATOR_H48_POLICY_NAME,
    B17_NEUROMODULATED_ENSEMBLE_H56_POLICY_NAME,
)
B17_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B17_FIXED_EVOLUTION_ATTEMPTS,
    B17_GENETIC_NEUROMODULATED_ENSEMBLE_H48_POLICY_NAME,
)
B18_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B18_ELIGIBILITY_TRACE_H48_POLICY_NAME,
    B18_METASTABLE_AROUSAL_H48_POLICY_NAME,
    B18_SYNAPTIC_TRACE_MODULATOR_H48_POLICY_NAME,
    B18_ELIGIBILITY_TRACE_H56_POLICY_NAME,
)
B18_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B18_FIXED_EVOLUTION_ATTEMPTS,
    B18_GENETIC_ELIGIBILITY_TRACE_H48_POLICY_NAME,
)
B19_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B19_EPISODIC_META_MEMORY_H48_POLICY_NAME,
    B19_STABILITY_MEMORY_H48_POLICY_NAME,
    B19_SWITCH_SUPPRESSION_H48_POLICY_NAME,
    B19_EPISODIC_META_MEMORY_H56_POLICY_NAME,
)
B19_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B19_FIXED_EVOLUTION_ATTEMPTS,
    B19_GENETIC_META_MEMORY_H48_POLICY_NAME,
)
B20_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B20_WORKING_MEMORY_GATE_H48_POLICY_NAME,
    B20_CONTEXT_BINDING_H48_POLICY_NAME,
    B20_STABILITY_BUFFER_H48_POLICY_NAME,
    B20_WORKING_MEMORY_GATE_H56_POLICY_NAME,
)
B20_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B20_FIXED_EVOLUTION_ATTEMPTS,
    B20_GENETIC_WORKING_MEMORY_H48_POLICY_NAME,
)
B21_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B21_HIPPOCAMPAL_REPLAY_H48_POLICY_NAME,
    B21_SEQUENCE_BINDING_H48_POLICY_NAME,
    B21_ROUTE_REHEARSAL_H48_POLICY_NAME,
    B21_HIPPOCAMPAL_REPLAY_H56_POLICY_NAME,
)
B21_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B21_FIXED_EVOLUTION_ATTEMPTS,
    B21_GENETIC_REPLAY_GATE_H48_POLICY_NAME,
)
B22_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B22_PROSPECTIVE_MAP_REPLAY_H48_POLICY_NAME,
    B22_FORWARD_MODEL_GATE_H48_POLICY_NAME,
    B22_ROUTE_VIABILITY_SIM_H48_POLICY_NAME,
    B22_PROSPECTIVE_MAP_REPLAY_H56_POLICY_NAME,
)
B22_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B22_FIXED_EVOLUTION_ATTEMPTS,
    B22_GENETIC_PROSPECTIVE_REPLAY_H48_POLICY_NAME,
)
B23_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B23_CONFLICT_MONITOR_H48_POLICY_NAME,
    B23_ERROR_GATED_REPLAY_H48_POLICY_NAME,
    B23_ABORT_CONFLICT_ARBITER_H48_POLICY_NAME,
    B23_CONFLICT_MONITOR_H56_POLICY_NAME,
)
B23_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B23_FIXED_EVOLUTION_ATTEMPTS,
    B23_GENETIC_CONFLICT_MONITOR_H48_POLICY_NAME,
)
B24_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B24_PRECISION_CONFLICT_H48_POLICY_NAME,
    B24_PREDICTION_PRECISION_GATE_H48_POLICY_NAME,
    B24_RELIABILITY_ABORT_H48_POLICY_NAME,
    B24_PRECISION_CONFLICT_H56_POLICY_NAME,
)
B24_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B24_FIXED_EVOLUTION_ATTEMPTS,
    B24_GENETIC_PRECISION_CONFLICT_H48_POLICY_NAME,
)
B25_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B25_METACOGNITIVE_CONFIDENCE_H48_POLICY_NAME,
    B25_CONFIDENCE_CALIBRATION_H48_POLICY_NAME,
    B25_UNCERTAINTY_INTEGRATOR_H48_POLICY_NAME,
    B25_METACOGNITIVE_CONFIDENCE_H56_POLICY_NAME,
)
B25_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B25_FIXED_EVOLUTION_ATTEMPTS,
    B25_GENETIC_METACOGNITION_H48_POLICY_NAME,
)
B26_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B26_ALLOSTATIC_PREDICTION_H48_POLICY_NAME,
    B26_SETPOINT_DRIFT_H48_POLICY_NAME,
    B26_ERROR_SUPPRESSION_H48_POLICY_NAME,
    B26_ALLOSTATIC_PREDICTION_H56_POLICY_NAME,
)
B26_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B26_FIXED_EVOLUTION_ATTEMPTS,
    B26_GENETIC_ALLOSTASIS_H48_POLICY_NAME,
)
B27_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B27_AROUSAL_GAIN_H48_POLICY_NAME,
    B27_STRESS_MODULATION_H48_POLICY_NAME,
    B27_ENERGY_AROUSAL_H48_POLICY_NAME,
    B27_AROUSAL_GAIN_H56_POLICY_NAME,
)
B27_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B27_FIXED_EVOLUTION_ATTEMPTS,
    B27_GENETIC_AROUSAL_H48_POLICY_NAME,
)
B28_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B28_INTEROCEPTIVE_ATTENTION_H48_POLICY_NAME,
    B28_THREAT_FOCUS_ATTENTION_H48_POLICY_NAME,
    B28_HOMEOSTATIC_ATTENTION_H48_POLICY_NAME,
    B28_INTEROCEPTIVE_ATTENTION_H56_POLICY_NAME,
)
B28_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B28_FIXED_EVOLUTION_ATTEMPTS,
    B28_GENETIC_ATTENTION_H48_POLICY_NAME,
)
B29_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B29_SALIENCE_COMPETITION_H48_POLICY_NAME,
    B29_THREAT_SALIENCE_GATE_H48_POLICY_NAME,
    B29_HOMEOSTATIC_SALIENCE_GATE_H48_POLICY_NAME,
    B29_SALIENCE_COMPETITION_H56_POLICY_NAME,
)
B29_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B29_FIXED_EVOLUTION_ATTEMPTS,
    B29_GENETIC_SALIENCE_H48_POLICY_NAME,
)
B30_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B30_BASAL_GANGLIA_GATE_H48_POLICY_NAME,
    B30_GO_NOGO_BALANCE_H48_POLICY_NAME,
    B30_THREAT_INHIBITION_GATE_H48_POLICY_NAME,
    B30_BASAL_GANGLIA_GATE_H56_POLICY_NAME,
)
B30_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B30_FIXED_EVOLUTION_ATTEMPTS,
    B30_GENETIC_ACTION_GATE_H48_POLICY_NAME,
)
B31_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B31_DOPAMINE_PREDICTION_ERROR_H48_POLICY_NAME,
    B31_TONIC_DOPAMINE_GATE_H48_POLICY_NAME,
    B31_PHASIC_DOPAMINE_GATE_H48_POLICY_NAME,
    B31_DOPAMINE_PREDICTION_ERROR_H56_POLICY_NAME,
)
B31_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B31_FIXED_EVOLUTION_ATTEMPTS,
    B31_GENETIC_DOPAMINE_GATE_H48_POLICY_NAME,
)
B32_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B32_ACTOR_CRITIC_VALUE_H48_POLICY_NAME,
    B32_ADVANTAGE_VALUE_GATE_H48_POLICY_NAME,
    B32_CRITIC_STABILITY_H48_POLICY_NAME,
    B32_ACTOR_CRITIC_VALUE_H56_POLICY_NAME,
)
B32_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B32_FIXED_EVOLUTION_ATTEMPTS,
    B32_GENETIC_ACTOR_CRITIC_H48_POLICY_NAME,
)
B33_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B33_TD_ERROR_DECOMPOSITION_H48_POLICY_NAME,
    B33_BOOTSTRAPPED_VALUE_GATE_H48_POLICY_NAME,
    B33_REWARD_TRACE_CRITIC_H48_POLICY_NAME,
    B33_TD_ERROR_DECOMPOSITION_H56_POLICY_NAME,
)
B33_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B33_FIXED_EVOLUTION_ATTEMPTS,
    B33_GENETIC_TD_VALUE_H48_POLICY_NAME,
)
B34_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B34_ELIGIBILITY_CREDIT_H48_POLICY_NAME,
    B34_DELAYED_CREDIT_GATE_H48_POLICY_NAME,
    B34_SYNAPTIC_TAGGING_H48_POLICY_NAME,
    B34_ELIGIBILITY_CREDIT_H56_POLICY_NAME,
)
B34_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B34_FIXED_EVOLUTION_ATTEMPTS,
    B34_GENETIC_ELIGIBILITY_H48_POLICY_NAME,
)
B35_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B35_FORWARD_MODEL_VALUE_H48_POLICY_NAME,
    B35_TRANSITION_ERROR_GATE_H48_POLICY_NAME,
    B35_MODEL_CONFIDENCE_H48_POLICY_NAME,
    B35_FORWARD_MODEL_VALUE_H56_POLICY_NAME,
)
B35_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B35_FIXED_EVOLUTION_ATTEMPTS,
    B35_GENETIC_FORWARD_MODEL_H48_POLICY_NAME,
)
B36_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B36_LATENT_BELIEF_STATE_H48_POLICY_NAME,
    B36_BELIEF_ERROR_GATE_H48_POLICY_NAME,
    B36_CONTEXT_INFERENCE_H48_POLICY_NAME,
    B36_LATENT_BELIEF_STATE_H56_POLICY_NAME,
)
B36_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B36_FIXED_EVOLUTION_ATTEMPTS,
    B36_GENETIC_BELIEF_STATE_H48_POLICY_NAME,
)
B37_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B37_STATE_FACTOR_GATE_H48_POLICY_NAME,
    B37_INTERO_EXTERO_FACTOR_H48_POLICY_NAME,
    B37_FACTOR_CONFIDENCE_H48_POLICY_NAME,
    B37_STATE_FACTOR_GATE_H56_POLICY_NAME,
)
B37_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B37_FIXED_EVOLUTION_ATTEMPTS,
    B37_GENETIC_STATE_FACTOR_H48_POLICY_NAME,
)
B38_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B38_FACTOR_ATTENTION_H48_POLICY_NAME,
    B38_INTEROCEPTIVE_ATTENTION_H48_POLICY_NAME,
    B38_CONFIDENCE_ATTENTION_H48_POLICY_NAME,
    B38_FACTOR_ATTENTION_H56_POLICY_NAME,
)
B38_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B38_FIXED_EVOLUTION_ATTEMPTS,
    B38_GENETIC_FACTOR_ATTENTION_H48_POLICY_NAME,
)
B39_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B39_ATTENTION_BINDING_H48_POLICY_NAME,
    B39_CROSS_FACTOR_BINDING_H48_POLICY_NAME,
    B39_CONTEXT_BINDING_ATTENTION_H48_POLICY_NAME,
    B39_ATTENTION_BINDING_H56_POLICY_NAME,
)
B39_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B39_FIXED_EVOLUTION_ATTEMPTS,
    B39_GENETIC_ATTENTION_BINDING_H48_POLICY_NAME,
)
B40_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B40_GLOBAL_WORKSPACE_H48_POLICY_NAME,
    B40_SENSORY_WORKSPACE_H48_POLICY_NAME,
    B40_CONTEXT_WORKSPACE_H48_POLICY_NAME,
    B40_GLOBAL_WORKSPACE_H56_POLICY_NAME,
)
B40_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B40_FIXED_EVOLUTION_ATTEMPTS,
    B40_GENETIC_GLOBAL_WORKSPACE_H48_POLICY_NAME,
)
B41_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B41_EXECUTIVE_WORKSPACE_H48_POLICY_NAME,
    B41_INHIBITORY_CONTROL_H48_POLICY_NAME,
    B41_GOAL_CONTEXT_SELECTOR_H48_POLICY_NAME,
    B41_EXECUTIVE_WORKSPACE_H56_POLICY_NAME,
)
B41_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B41_FIXED_EVOLUTION_ATTEMPTS,
    B41_GENETIC_EXECUTIVE_WORKSPACE_H48_POLICY_NAME,
)
B42_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B42_ERROR_MONITOR_H48_POLICY_NAME,
    B42_CONFLICT_MONITOR_H48_POLICY_NAME,
    B42_PERFORMANCE_MONITOR_H48_POLICY_NAME,
    B42_ERROR_MONITOR_H56_POLICY_NAME,
)
B42_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B42_FIXED_EVOLUTION_ATTEMPTS,
    B42_GENETIC_ERROR_MONITOR_H48_POLICY_NAME,
)
B43_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B43_ADAPTIVE_PRECISION_H48_POLICY_NAME,
    B43_AROUSAL_PRECISION_H48_POLICY_NAME,
    B43_THRESHOLD_ADAPTATION_H48_POLICY_NAME,
    B43_ADAPTIVE_PRECISION_H56_POLICY_NAME,
)
B43_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B43_FIXED_EVOLUTION_ATTEMPTS,
    B43_GENETIC_ADAPTIVE_PRECISION_H48_POLICY_NAME,
)
B44_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B44_THALAMIC_RELAY_H48_POLICY_NAME,
    B44_SENSORY_RELAY_H48_POLICY_NAME,
    B44_CONTEXT_RELAY_H48_POLICY_NAME,
    B44_THALAMIC_RELAY_H56_POLICY_NAME,
)
B44_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B44_FIXED_EVOLUTION_ATTEMPTS,
    B44_GENETIC_THALAMIC_RELAY_H48_POLICY_NAME,
)
B45_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B45_RETICULAR_INHIBITION_H48_POLICY_NAME,
    B45_SENSORY_INHIBITION_H48_POLICY_NAME,
    B45_CONTEXT_INHIBITION_H48_POLICY_NAME,
    B45_RETICULAR_INHIBITION_H56_POLICY_NAME,
)
B45_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B45_FIXED_EVOLUTION_ATTEMPTS,
    B45_GENETIC_RETICULAR_INHIBITION_H48_POLICY_NAME,
)
B46_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B46_CORTICOTHALAMIC_FEEDBACK_H48_POLICY_NAME,
    B46_FEEDBACK_GAIN_H48_POLICY_NAME,
    B46_CONTEXT_FEEDBACK_H48_POLICY_NAME,
    B46_CORTICOTHALAMIC_FEEDBACK_H56_POLICY_NAME,
)
B46_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B46_FIXED_EVOLUTION_ATTEMPTS,
    B46_GENETIC_CORTICOTHALAMIC_FEEDBACK_H48_POLICY_NAME,
)
B47_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B47_OSCILLATORY_SYNCHRONY_H48_POLICY_NAME,
    B47_PHASE_LOCKING_H48_POLICY_NAME,
    B47_COHERENCE_GATE_H48_POLICY_NAME,
    B47_OSCILLATORY_SYNCHRONY_H56_POLICY_NAME,
)
B47_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B47_FIXED_EVOLUTION_ATTEMPTS,
    B47_GENETIC_OSCILLATORY_SYNCHRONY_H48_POLICY_NAME,
)
B48_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B48_CEREBELLAR_TIMING_H48_POLICY_NAME,
    B48_TIMING_ERROR_CORRECTION_H48_POLICY_NAME,
    B48_PREDICTIVE_TIMING_H48_POLICY_NAME,
    B48_CEREBELLAR_TIMING_H56_POLICY_NAME,
)
B48_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B48_FIXED_EVOLUTION_ATTEMPTS,
    B48_GENETIC_CEREBELLAR_TIMING_H48_POLICY_NAME,
)
B49_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B49_STRIATAL_ACTION_GATE_H48_POLICY_NAME,
    B49_DIRECT_PATH_FACILITATION_H48_POLICY_NAME,
    B49_INDIRECT_PATH_SUPPRESSION_H48_POLICY_NAME,
    B49_STRIATAL_ACTION_GATE_H56_POLICY_NAME,
)
B49_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B49_FIXED_EVOLUTION_ATTEMPTS,
    B49_GENETIC_STRIATAL_GATE_H48_POLICY_NAME,
)
B50_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B50_HABIT_CHUNKING_H48_POLICY_NAME,
    B50_ACTION_CHUNK_VALUE_H48_POLICY_NAME,
    B50_HABIT_STABILITY_H48_POLICY_NAME,
    B50_HABIT_CHUNKING_H56_POLICY_NAME,
)
B50_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B50_FIXED_EVOLUTION_ATTEMPTS,
    B50_GENETIC_HABIT_CHUNKING_H48_POLICY_NAME,
)
B51_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B51_DOPAMINERGIC_HABIT_MODULATION_H48_POLICY_NAME,
    B51_REWARD_PREDICTION_GAIN_H48_POLICY_NAME,
    B51_NOVELTY_MODULATED_HABIT_H48_POLICY_NAME,
    B51_DOPAMINERGIC_HABIT_MODULATION_H56_POLICY_NAME,
)
B51_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B51_FIXED_EVOLUTION_ATTEMPTS,
    B51_GENETIC_DOPAMINE_HABIT_H48_POLICY_NAME,
)
B52_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B52_CHOLINERGIC_PRECISION_GATE_H48_POLICY_NAME,
    B52_ATTENTION_GAIN_H48_POLICY_NAME,
    B52_UNCERTAINTY_RELEASE_H48_POLICY_NAME,
    B52_CHOLINERGIC_PRECISION_GATE_H56_POLICY_NAME,
)
B52_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B52_FIXED_EVOLUTION_ATTEMPTS,
    B52_GENETIC_CHOLINERGIC_PRECISION_H48_POLICY_NAME,
)
B53_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B53_NORADRENERGIC_AROUSAL_GAIN_H48_POLICY_NAME,
    B53_SURPRISE_GAIN_H48_POLICY_NAME,
    B53_STRESS_PRECISION_H48_POLICY_NAME,
    B53_NORADRENERGIC_AROUSAL_GAIN_H56_POLICY_NAME,
)
B53_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B53_FIXED_EVOLUTION_ATTEMPTS,
    B53_GENETIC_AROUSAL_PRECISION_H48_POLICY_NAME,
)
B54_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B54_SEROTONERGIC_PATIENCE_GATE_H48_POLICY_NAME,
    B54_IMPULSE_SUPPRESSION_H48_POLICY_NAME,
    B54_PATIENCE_BALANCE_H48_POLICY_NAME,
    B54_SEROTONERGIC_PATIENCE_GATE_H56_POLICY_NAME,
)
B54_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B54_FIXED_EVOLUTION_ATTEMPTS,
    B54_GENETIC_SEROTONIN_PATIENCE_H48_POLICY_NAME,
)
B55_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B55_HYPOTHALAMIC_DRIVE_COUPLING_H48_POLICY_NAME,
    B55_SATIETY_RECOVERY_BALANCE_H48_POLICY_NAME,
    B55_SLEEP_HUNGER_ARBITER_H48_POLICY_NAME,
    B55_HYPOTHALAMIC_DRIVE_COUPLING_H56_POLICY_NAME,
)
B55_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B55_FIXED_EVOLUTION_ATTEMPTS,
    B55_GENETIC_HYPOTHALAMIC_DRIVE_H48_POLICY_NAME,
)
B56_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B56_HPA_STRESS_AXIS_H48_POLICY_NAME,
    B56_CORTISOL_RECOVERY_BALANCE_H48_POLICY_NAME,
    B56_STRESS_LOAD_GATE_H48_POLICY_NAME,
    B56_HPA_STRESS_AXIS_H56_POLICY_NAME,
)
B56_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B56_FIXED_EVOLUTION_ATTEMPTS,
    B56_GENETIC_HPA_STRESS_H48_POLICY_NAME,
)
B57_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B57_INSULAR_INTEROCEPTIVE_AWARENESS_H48_POLICY_NAME,
    B57_VISCERAL_SALIENCE_GATE_H48_POLICY_NAME,
    B57_STRESS_DRIVE_AWARENESS_H48_POLICY_NAME,
    B57_INSULAR_INTEROCEPTIVE_AWARENESS_H56_POLICY_NAME,
)
B57_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B57_FIXED_EVOLUTION_ATTEMPTS,
    B57_GENETIC_INTEROCEPTIVE_AWARENESS_H48_POLICY_NAME,
)
B58_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B58_ACC_CONFLICT_MONITOR_H48_POLICY_NAME,
    B58_ERROR_SALIENCE_GATE_H48_POLICY_NAME,
    B58_CONFLICT_RESOLUTION_BALANCE_H48_POLICY_NAME,
    B58_ACC_CONFLICT_MONITOR_H56_POLICY_NAME,
)
B58_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B58_FIXED_EVOLUTION_ATTEMPTS,
    B58_GENETIC_ACC_CONFLICT_H48_POLICY_NAME,
)
B59_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B59_PREFRONTAL_GOAL_CONTEXT_H48_POLICY_NAME,
    B59_WORKING_SET_STABILITY_H48_POLICY_NAME,
    B59_EXECUTIVE_TASK_SET_H48_POLICY_NAME,
    B59_PREFRONTAL_GOAL_CONTEXT_H56_POLICY_NAME,
)
B59_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B59_FIXED_EVOLUTION_ATTEMPTS,
    B59_GENETIC_PREFRONTAL_CONTROL_H48_POLICY_NAME,
)
B60_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B60_ORBITOFRONTAL_OUTCOME_VALUE_H48_POLICY_NAME,
    B60_REVERSAL_VALUE_GATE_H48_POLICY_NAME,
    B60_GOAL_OUTCOME_PREDICTION_H48_POLICY_NAME,
    B60_ORBITOFRONTAL_OUTCOME_VALUE_H56_POLICY_NAME,
)
B60_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B60_FIXED_EVOLUTION_ATTEMPTS,
    B60_GENETIC_ORBITOFRONTAL_VALUE_H48_POLICY_NAME,
)
B61_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B61_AMYGDALA_SAFETY_VALUE_H48_POLICY_NAME,
    B61_THREAT_VALUE_TAG_H48_POLICY_NAME,
    B61_SAFETY_PREDICTION_GATE_H48_POLICY_NAME,
    B61_AMYGDALA_SAFETY_VALUE_H56_POLICY_NAME,
)
B61_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B61_FIXED_EVOLUTION_ATTEMPTS,
    B61_GENETIC_AMYGDALA_SAFETY_H48_POLICY_NAME,
)
B62_FIXED_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    B62_DEFENSIVE_MODE_SELECTOR_H48_POLICY_NAME,
    B62_FREEZE_FLEE_BALANCE_H48_POLICY_NAME,
    B62_SHELTER_DEFENSE_GATE_H48_POLICY_NAME,
    B62_DEFENSIVE_MODE_SELECTOR_H56_POLICY_NAME,
)
B62_EVOLUTION_ATTEMPTS: tuple[str, ...] = (
    *B62_FIXED_EVOLUTION_ATTEMPTS,
    B62_GENETIC_DEFENSIVE_MODE_H48_POLICY_NAME,
)
B1_EASY_SCENARIO = "continuous_survival_easy_v1"
B1_CANONICAL_SCENARIO = "continuous_survival_canonical"
B2_CANONICAL_BASELINE = {
    "steps": 69,
    "food_eaten": 3,
    "sleep_events": 3,
    "shelter_entries": 5,
    "predator_contacts": 5,
}
B2_EASY_EVALUATION_EPISODE = 0
B2_CANONICAL_EVALUATION_EPISODE = 0
B2_CANONICAL_MIN_STEPS = 100
B2_CANONICAL_MAX_PREDATOR_CONTACTS = 4
B3_EASY_EVALUATION_EPISODE = 0
B3_CANONICAL_EVALUATION_EPISODES: tuple[int, ...] = (0, 1)
B3_CANONICAL_MAX_PREDATOR_CONTACTS_EP0 = 6
B3_CANONICAL_MAX_PREDATOR_CONTACTS_EP1 = 4
B3_CANONICAL_BASELINES: dict[int, dict[str, object]] = {
    0: {
        "steps": 300,
        "alive": True,
        "food_eaten": 13,
        "sleep_events": 46,
        "shelter_entries": 12,
        "predator_contacts": 9,
    },
    1: {
        "steps": 105,
        "alive": False,
        "food_eaten": 6,
        "sleep_events": 3,
        "shelter_entries": 5,
        "predator_contacts": 5,
    },
}
B4_EASY_EVALUATION_EPISODES: tuple[int, ...] = (0, 1, 2, 3, 4)
B4_CANONICAL_EVALUATION_EPISODES: tuple[int, ...] = tuple(range(10))
B4_CANONICAL_BASELINE = {
    "completed_horizon_count": 4,
    "min_steps": 49,
    "total_predator_contacts": 26,
}
B4_CANONICAL_MIN_COMPLETED_HORIZONS = int(
    B4_CANONICAL_BASELINE["completed_horizon_count"]
)
B4_CANONICAL_MIN_STEPS = int(B4_CANONICAL_BASELINE["min_steps"])
B4_CANONICAL_MAX_TOTAL_PREDATOR_CONTACTS = int(
    B4_CANONICAL_BASELINE["total_predator_contacts"]
)
B4_CANONICAL_MIN_FOOD_CYCLE_EPISODES = 9
B4_CANONICAL_MIN_SLEEP_CYCLE_EPISODES = 9
B4_CANONICAL_MIN_SHELTER_CYCLE_EPISODES = 10
B5_FOOD_DEPRIVATION_SCENARIO = "food_deprivation"
B5_SLEEP_CONFLICT_SCENARIO = "sleep_vs_exploration_conflict"
B5_DIAGNOSTIC_SCENARIOS: tuple[str, ...] = (
    "food_vs_predator_conflict",
    "corridor_gauntlet",
)
B5_PROBE_EVALUATION_EPISODES: tuple[int, ...] = (0, 1, 2)
B6_FOOD_PREDATOR_SCENARIO = "food_vs_predator_conflict"
B6_CORRIDOR_SCENARIO = "corridor_gauntlet"
B6_PROBE_EVALUATION_EPISODES: tuple[int, ...] = (0, 1, 2)
B6_CORRIDOR_BASELINE_STEPS = 14
B6_CORRIDOR_BASELINE_FOOD_DISTANCE_DELTA = 12.0
B7_CORRIDOR_REQUIRED_FOOD_DISTANCE_DELTA = 13.0
B7_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "continue_viable",
    "abort_return_unviable",
    "recover_before_crossing",
)
B8_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "corridor_continue_mapped",
    "corridor_abort_signal",
    "corridor_hold_unviable",
)
B9_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "commit_food_waypoint",
    "continue_locked_waypoint",
    "replan_return",
)
B10_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "commit_replayed_route",
    "continue_replay_commitment",
    "abort_failed_rollout",
)
B11_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "commit_confident_plan",
    "continue_confidence_lock",
    "gate_uncertain_plan",
)
B12_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "commit_attended_affordance",
    "continue_attention_lock",
    "gate_prediction_error",
)
B13_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "commit_local_affordance_search",
    "continue_local_search_lock",
    "abort_local_dead_end",
)
B14_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "commit_confident_affordance",
    "continue_confidence_lock",
    "return_on_affordance_uncertainty",
)
B15_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "persist_food_option",
    "continue_option_lock",
    "terminate_uncertain_option",
)
B16_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "ensemble_continue_option",
    "continue_ensemble_lock",
    "ensemble_return_option",
)
B17_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "neuromodulated_continue",
    "continue_modulation_lock",
    "neuromodulated_return",
)
B18_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "eligibility_stabilize_option",
    "continue_trace_lock",
    "eligibility_release_option",
)
B19_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "episodic_consolidate_option",
    "continue_memory_lock",
    "episodic_release_option",
)
B20_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "working_memory_gate_continue",
    "continue_working_memory_lock",
    "working_memory_gate_release",
)
B21_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "hippocampal_replay_continue",
    "continue_replay_lock",
    "hippocampal_replay_abort",
)
B22_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "prospective_replay_continue",
    "continue_prospective_lock",
    "prospective_replay_abort",
)
B23_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "conflict_monitor_continue",
    "continue_conflict_lock",
    "conflict_monitor_abort",
)
B24_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "precision_conflict_continue",
    "continue_precision_lock",
    "precision_conflict_abort",
)
B25_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "metacognitive_confidence_continue",
    "continue_meta_lock",
    "metacognitive_confidence_abort",
)
B26_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "allostatic_prediction_continue",
    "continue_allostatic_lock",
    "allostatic_prediction_abort",
)
B27_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "arousal_gain_continue",
    "continue_arousal_lock",
    "arousal_gain_abort",
)
B28_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "interoceptive_attention_continue",
    "continue_attention_lock",
    "interoceptive_attention_abort",
)
B29_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "salience_competition_continue",
    "continue_salience_lock",
    "salience_competition_abort",
)
B30_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "basal_gate_go",
    "continue_basal_gate_lock",
    "basal_gate_no_go",
)
B31_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "dopamine_gate_go",
    "continue_dopamine_lock",
    "dopamine_gate_no_go",
)
B32_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "actor_critic_commit",
    "continue_value_lock",
    "critic_abort_negative_value",
)
B33_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "td_error_commit",
    "continue_td_lock",
    "td_error_abort",
)
B34_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "eligibility_credit_commit",
    "continue_eligibility_lock",
    "eligibility_credit_abort",
)
B35_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "forward_model_commit",
    "continue_model_lock",
    "forward_model_abort",
)
B36_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "latent_belief_commit",
    "continue_belief_lock",
    "latent_belief_abort",
)
B37_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "state_factor_commit",
    "continue_factor_lock",
    "state_factor_abort",
)
B38_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "factor_attention_commit",
    "continue_attention_lock",
    "factor_attention_abort",
)
B39_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "attention_binding_commit",
    "continue_binding_lock",
    "attention_binding_abort",
)
B40_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "global_workspace_commit",
    "continue_workspace_lock",
    "global_workspace_abort",
)
B41_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "executive_workspace_select",
    "continue_executive_lock",
    "executive_workspace_abort",
)
B42_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "error_monitor_commit",
    "continue_monitor_lock",
    "error_monitor_abort",
)
B43_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "adaptive_precision_commit",
    "continue_precision_lock",
    "adaptive_precision_abort",
)
B44_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "thalamic_relay_commit",
    "continue_relay_lock",
    "thalamic_relay_abort",
)
B45_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "reticular_inhibition_commit",
    "continue_inhibition_lock",
    "reticular_inhibition_abort",
)
B46_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "corticothalamic_feedback_commit",
    "continue_feedback_lock",
    "corticothalamic_feedback_abort",
)
B47_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "oscillatory_synchrony_commit",
    "continue_phase_lock",
    "oscillatory_synchrony_abort",
)
B48_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "cerebellar_timing_commit",
    "continue_calibration_lock",
    "cerebellar_timing_abort",
)
B49_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "striatal_gate_commit",
    "continue_selection_lock",
    "striatal_gate_abort",
)
B50_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "habit_chunk_commit",
    "continue_habit_chunk",
    "habit_chunk_abort",
)
B51_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "dopamine_habit_commit",
    "continue_dopamine_modulation",
    "dopamine_habit_abort",
)
B52_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "cholinergic_precision_commit",
    "continue_precision_attention",
    "cholinergic_precision_abort",
)
B53_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "noradrenergic_arousal_commit",
    "continue_arousal_gain",
    "noradrenergic_arousal_abort",
)
B54_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "serotonergic_patience_commit",
    "continue_patience_lock",
    "serotonergic_patience_abort",
)
B55_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "hypothalamic_drive_commit",
    "continue_drive_lock",
    "hypothalamic_drive_abort",
)
B56_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "hpa_stress_axis_commit",
    "continue_stress_axis_lock",
    "hpa_stress_axis_abort",
)
B57_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "interoceptive_awareness_commit",
    "continue_awareness_lock",
    "interoceptive_awareness_abort",
)
B58_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "acc_conflict_commit",
    "continue_conflict_lock",
    "acc_conflict_abort",
)
B59_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "prefrontal_goal_commit",
    "continue_executive_lock",
    "prefrontal_goal_abort",
)
B60_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "orbitofrontal_value_commit",
    "continue_value_lock",
    "orbitofrontal_value_reversal",
)
B61_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "amygdala_safety_commit",
    "continue_safety_lock",
    "amygdala_threat_reversal",
)
B62_CORRIDOR_EXPLICIT_DECISIONS: tuple[str, ...] = (
    "defensive_flee_to_shelter",
    "defensive_freeze_hold",
    "continue_defense_lock",
    "defensive_safe_advance",
)
