from __future__ import annotations

from .perception_targets import (
    VisibilityZone,
    HasPosition,
    PerceivedTarget,
    NO_TARGET_DISTANCE,
    DOMINANT_PREDATOR_TYPE_NONE,
    DOMINANT_PREDATOR_TYPE_VISUAL,
    DOMINANT_PREDATOR_TYPE_OLFACTORY,
    TERRAIN_DIFFICULTY,
)
from .perception_audit import (
    OBSERVATION_LEAKAGE_AUDIT,
    observation_leakage_audit,
)
from .perception_geometry import (
    _clip_signed,
    _fov_thresholds,
    _max_scan_age,
    _normalized_scan_age,
    _compute_target_visibility_zone,
    _heading_allows_target,
    _percept_trace_ttl,
    _percept_trace_decay,
    trace_strength,
    PERCEPTION_CATEGORY_CERTAINTY_THRESHOLD,
    _perception_category,
    _apply_visibility_zone_certainty,
    _apply_visual_noise,
    _apply_olfactory_noise,
    visible_range,
    visibility_confidence,
    line_cells,
    has_line_of_sight,
    visible_object,
    smell_gradient,
)
from .perception_trace import (
    empty_percept_trace,
    trace_view,
    advance_percept_trace,
)
from .perception_predators import (
    predator_motion_salience,
    _predator_candidates,
    _predator_position,
    _uses_world_level_profile,
    _predator_profile_fields,
    _predator_detection_style,
    _predator_for_position,
    _predator_visual_view,
    _no_target_perceived_target,
    _normalized_proximity,
    _visual_threat_score,
    _select_best_predator_view,
    _predator_view_tie_break,
    _sample_predator_views,
    _predator_views_by_type_from_sampled_views,
    predators_visible_to_spider,
    _predator_view_from_views,
    predator_detects_spider,
    lizard_detects_spider,
    predator_visible_to_spider,
    compute_per_type_threats,
)
from .perception_observations import (
    _unpack_trace_view,
    serialize_observation_view,
    build_visual_observation,
    build_sensory_observation,
    build_hunger_observation,
    build_sleep_observation,
    build_alert_observation,
    build_action_context_observation,
    build_motor_context_observation,
    observe_world,
)
