from __future__ import annotations

from .runtime_shared import *
from .runtime_act_payload import _BrainRuntimeActPayloadMixin
from .runtime_action_loop import _BrainRuntimePart10Mixin
from .runtime_b0_b6_semantics import _BrainRuntimePart1Mixin
from .runtime_b6_b14_semantics import _BrainRuntimePart2Mixin
from .runtime_b14_b23_semantics import _BrainRuntimePart3Mixin
from .runtime_b23_b31_semantics import _BrainRuntimePart4Mixin
from .runtime_b32_b40_semantics import _BrainRuntimePart5Mixin
from .runtime_b40_b48_semantics import _BrainRuntimePart6Mixin
from .runtime_b48_b56_semantics import _BrainRuntimePart7Mixin
from .runtime_b56_b62_compute import _BrainRuntimePart8Mixin
from .runtime_control_modes import _BrainRuntimePart9Mixin
from .runtime_introspection import _BrainRuntimePart11Mixin


class BrainRuntimeMixin(_BrainRuntimeActPayloadMixin, _BrainRuntimePart1Mixin, _BrainRuntimePart2Mixin, _BrainRuntimePart3Mixin, _BrainRuntimePart4Mixin, _BrainRuntimePart5Mixin, _BrainRuntimePart6Mixin, _BrainRuntimePart7Mixin, _BrainRuntimePart8Mixin, _BrainRuntimePart9Mixin, _BrainRuntimePart10Mixin, _BrainRuntimePart11Mixin):
    pass
