from __future__ import annotations

from .runtime_shared import *
from .runtime_act_payload import _BrainRuntimeActPayloadMixin
from .runtime_action_loop import _BrainRuntimePart10Mixin
from .runtime_b0_b6_semantics import _BrainRuntimePart1Mixin
from .runtime_b6_b14_semantics import _BrainRuntimePart2Mixin
from .runtime_b14_b23_semantics import _BrainRuntimePart3Mixin
from .runtime_b23_b31_semantics import _BrainRuntimePart4Mixin
from .runtime_b32_b40_semantics import _BrainRuntimePart5Mixin
from .runtime_b40_b48_semantics import _BrainRuntimePart6Mixin
from .runtime_b48_b56_semantics import _BrainRuntimePart7Mixin
from .runtime_b56_b62_compute import _BrainRuntimePart8Mixin
from .runtime_b65_semantics import _BrainRuntimePart8bMixin
from .runtime_b66_semantics import _BrainRuntimePart8cMixin
from .runtime_b67_semantics import _BrainRuntimePart8dMixin
from .runtime_b68_semantics import _BrainRuntimePart8eMixin
from .runtime_b69_semantics import _BrainRuntimePart8fMixin
from .runtime_b70_semantics import _BrainRuntimePart8gMixin
from .runtime_b71_semantics import _BrainRuntimePart8hMixin
from .runtime_b72_semantics import _BrainRuntimePart8iMixin
from .runtime_b73_semantics import _BrainRuntimePart8jMixin
from .runtime_b74_semantics import _BrainRuntimePart8kMixin
from .runtime_b75_semantics import _BrainRuntimePart8lMixin
from .runtime_b76_semantics import _BrainRuntimePart8mMixin
from .runtime_b77_semantics import _BrainRuntimePart8nMixin
from .runtime_b78_semantics import _BrainRuntimePart8oMixin
from .runtime_control_modes import _BrainRuntimePart9Mixin
from .runtime_introspection import _BrainRuntimePart11Mixin


class BrainRuntimeMixin(_BrainRuntimeActPayloadMixin, _BrainRuntimePart1Mixin, _BrainRuntimePart2Mixin, _BrainRuntimePart3Mixin, _BrainRuntimePart4Mixin, _BrainRuntimePart5Mixin, _BrainRuntimePart6Mixin, _BrainRuntimePart7Mixin, _BrainRuntimePart8Mixin, _BrainRuntimePart8bMixin, _BrainRuntimePart8cMixin, _BrainRuntimePart8dMixin, _BrainRuntimePart8eMixin, _BrainRuntimePart8fMixin, _BrainRuntimePart8gMixin, _BrainRuntimePart8hMixin, _BrainRuntimePart8iMixin, _BrainRuntimePart8jMixin, _BrainRuntimePart8kMixin, _BrainRuntimePart8lMixin, _BrainRuntimePart8mMixin, _BrainRuntimePart8nMixin, _BrainRuntimePart8oMixin, _BrainRuntimePart9Mixin, _BrainRuntimePart10Mixin, _BrainRuntimePart11Mixin):
    pass
