from __future__ import annotations

from .runtime_shared import *


_B_SERIES_STEP_PAYLOAD_FIELDS = (
    'b_current_threat_pressure',
    'b_temporal_threat_pressure',
    'b_predator_memory_pressure',
    'b_predator_trace_pressure',
    'b3_contact_cooldown',
    'b3_post_food_cooldown',
    'b3_hunger_drop',
    'b3_controller_profile',
    'b4_controller_profile',
    'b4_recovery_pressure',
    'b4_sleep_hold',
    'b4_exit_blocked',
    'b4_hunger_release',
    'b4_genetic_generation',
    'b4_genetic_candidate',
    'b5_controller_profile',
    'b5_hunger_urgency',
    'b5_sleep_pressure',
    'b5_recovery_debt',
    'b5_threat_gate',
    'b5_sleep_bout_lock',
    'b5_forage_commitment_lock',
    'b5_homeostatic_decision',
    'b5_genetic_generation',
    'b5_genetic_candidate',
    'b6_controller_family',
    'b6_controller_profile',
    'b6_risk_pressure',
    'b6_threat_priority',
    'b6_forage_suppressed',
    'b6_corridor_commitment',
    'b6_corridor_progress_memory',
    'b6_recurrent_state',
    'b6_return_lock',
    'b6_decision',
    'b6_genetic_generation',
    'b6_genetic_candidate',
    'b7_controller_profile',
    'b7_affordance_state',
    'b7_energy_budget',
    'b7_budget_margin',
    'b7_food_steps_estimate',
    'b7_return_steps_estimate',
    'b7_corridor_viability',
    'b7_abort_return',
    'b7_commitment_lock',
    'b7_decision',
    'b7_genetic_generation',
    'b7_genetic_candidate',
    'b8_controller_profile',
    'b8_spatial_map_state',
    'b8_local_affordance_score',
    'b8_return_vector_strength',
    'b8_corridor_dead_end_risk',
    'b8_abort_executed',
    'b8_place_memory',
    'b8_decision',
    'b8_genetic_generation',
    'b8_genetic_candidate',
    'b9_controller_profile',
    'b9_route_state',
    'b9_route_confidence',
    'b9_waypoint_lock',
    'b9_path_integrator',
    'b9_replan_signal',
    'b9_decision',
    'b9_genetic_generation',
    'b9_genetic_candidate',
    'b10_controller_profile',
    'b10_replay_state',
    'b10_prospective_value',
    'b10_rollout_depth',
    'b10_replay_memory',
    'b10_plan_commitment',
    'b10_abort_signal',
    'b10_decision',
    'b10_genetic_generation',
    'b10_genetic_candidate',
    'b11_controller_profile',
    'b11_confidence_state',
    'b11_plan_confidence',
    'b11_uncertainty',
    'b11_neuromod_signal',
    'b11_confidence_lock',
    'b11_decision',
    'b11_genetic_generation',
    'b11_genetic_candidate',
    'b12_controller_profile',
    'b12_attention_state',
    'b12_prediction_error',
    'b12_attention_gain',
    'b12_expected_progress',
    'b12_search_lock',
    'b12_decision',
    'b12_genetic_generation',
    'b12_genetic_candidate',
    'b13_controller_profile',
    'b13_search_state',
    'b13_local_route_score',
    'b13_affordance_samples',
    'b13_search_memory',
    'b13_dead_end_score',
    'b13_search_lock',
    'b13_decision',
    'b13_genetic_generation',
    'b13_genetic_candidate',
    'b14_controller_profile',
    'b14_uncertainty_state',
    'b14_affordance_confidence',
    'b14_uncertainty',
    'b14_risk_adjusted_score',
    'b14_commitment_lock',
    'b14_decision',
    'b14_genetic_generation',
    'b14_genetic_candidate',
    'b15_controller_profile',
    'b15_option_state',
    'b15_option_value',
    'b15_termination_pressure',
    'b15_persistence_score',
    'b15_option_lock',
    'b15_decision',
    'b15_genetic_generation',
    'b15_genetic_candidate',
    'b16_controller_profile',
    'b16_ensemble_state',
    'b16_continue_vote',
    'b16_return_vote',
    'b16_option_votes',
    'b16_consensus_score',
    'b16_conflict_score',
    'b16_ensemble_lock',
    'b16_decision',
    'b16_genetic_generation',
    'b16_genetic_candidate',
    'b17_controller_profile',
    'b17_modulator_state',
    'b17_arousal_signal',
    'b17_homeostatic_gain',
    'b17_option_gain',
    'b17_conflict_release',
    'b17_modulation_lock',
    'b17_decision',
    'b17_genetic_generation',
    'b17_genetic_candidate',
    'b18_controller_profile',
    'b18_trace_state',
    'b18_eligibility_trace',
    'b18_reward_prediction_proxy',
    'b18_stability_bias',
    'b18_switch_pressure',
    'b18_trace_lock',
    'b18_decision',
    'b18_genetic_generation',
    'b18_genetic_candidate',
    'b19_controller_profile',
    'b19_memory_state',
    'b19_episode_memory',
    'b19_consolidation_score',
    'b19_stability_vote',
    'b19_switch_suppression',
    'b19_memory_lock',
    'b19_decision',
    'b19_genetic_generation',
    'b19_genetic_candidate',
    'b20_controller_profile',
    'b20_buffer_state',
    'b20_working_buffer',
    'b20_context_binding',
    'b20_gate_vote',
    'b20_release_vote',
    'b20_buffer_lock',
    'b20_decision',
    'b20_genetic_generation',
    'b20_genetic_candidate',
    'b21_controller_profile',
    'b21_replay_state',
    'b21_sequence_memory',
    'b21_replay_score',
    'b21_route_commitment',
    'b21_abort_prediction',
    'b21_replay_lock',
    'b21_decision',
    'b21_genetic_generation',
    'b21_genetic_candidate',
    'b22_controller_profile',
    'b22_sim_state',
    'b22_prospective_sim',
    'b22_forward_model_score',
    'b22_viability_projection',
    'b22_abort_projection',
    'b22_sim_lock',
    'b22_decision',
    'b22_genetic_generation',
    'b22_genetic_candidate',
    'b23_controller_profile',
    'b23_conflict_state',
    'b23_prediction_error',
    'b23_conflict_memory',
    'b23_stability_vote',
    'b23_abort_bias',
    'b23_monitor_lock',
    'b23_decision',
    'b23_genetic_generation',
    'b23_genetic_candidate',
    'b24_controller_profile',
    'b24_precision_state',
    'b24_precision_memory',
    'b24_precision_vote',
    'b24_uncertainty_pressure',
    'b24_abort_precision',
    'b24_precision_lock',
    'b24_decision',
    'b24_genetic_generation',
    'b24_genetic_candidate',
    'b25_controller_profile',
    'b25_metacognitive_state',
    'b25_confidence_memory',
    'b25_confidence_vote',
    'b25_doubt_pressure',
    'b25_control_gain',
    'b25_meta_lock',
    'b25_decision',
    'b25_genetic_generation',
    'b25_genetic_candidate',
    'b26_controller_profile',
    'b26_allostatic_state',
    'b26_prediction_error',
    'b26_setpoint_pressure',
    'b26_control_vote',
    'b26_stability_lock',
    'b26_decision',
    'b26_genetic_generation',
    'b26_genetic_candidate',
    'b27_controller_profile',
    'b27_arousal_state',
    'b27_arousal_level',
    'b27_gain_modulation',
    'b27_stress_pressure',
    'b27_arousal_lock',
    'b27_decision',
    'b27_genetic_generation',
    'b27_genetic_candidate',
    'b28_controller_profile',
    'b28_attention_state',
    'b28_interoceptive_focus',
    'b28_attention_gain',
    'b28_distractor_pressure',
    'b28_attention_lock',
    'b28_decision',
    'b28_genetic_generation',
    'b28_genetic_candidate',
    'b29_controller_profile',
    'b29_salience_state',
    'b29_threat_salience',
    'b29_homeostatic_salience',
    'b29_corridor_salience',
    'b29_winner_channel',
    'b29_salience_lock',
    'b29_decision',
    'b29_genetic_generation',
    'b29_genetic_candidate',
    'b30_controller_profile',
    'b30_gate_state',
    'b30_go_signal',
    'b30_no_go_signal',
    'b30_action_gate',
    'b30_gate_lock',
    'b30_decision',
    'b30_genetic_generation',
    'b30_genetic_candidate',
    'b31_controller_profile',
    'b31_dopamine_state',
    'b31_reward_prediction_error',
    'b31_tonic_dopamine',
    'b31_phasic_dopamine',
    'b31_gate_bias',
    'b31_dopamine_lock',
    'b31_decision',
    'b31_genetic_generation',
    'b31_genetic_candidate',
    'b32_controller_profile',
    'b32_critic_value',
    'b32_actor_advantage',
    'b32_value_error',
    'b32_policy_bias',
    'b32_value_lock',
    'b32_decision',
    'b32_genetic_generation',
    'b32_genetic_candidate',
    'b33_controller_profile',
    'b33_td_error',
    'b33_bootstrap_value',
    'b33_reward_trace',
    'b33_actor_update',
    'b33_td_lock',
    'b33_decision',
    'b33_genetic_generation',
    'b33_genetic_candidate',
    'b34_controller_profile',
    'b34_eligibility_trace',
    'b34_credit_assignment',
    'b34_synaptic_tag',
    'b34_decay_memory',
    'b34_credit_lock',
    'b34_decision',
    'b34_genetic_generation',
    'b34_genetic_candidate',
    'b35_controller_profile',
    'b35_forward_value',
    'b35_transition_error',
    'b35_model_confidence',
    'b35_prediction_memory',
    'b35_model_lock',
    'b35_decision',
    'b35_genetic_generation',
    'b35_genetic_candidate',
    'b36_controller_profile',
    'b36_latent_state',
    'b36_belief_error',
    'b36_state_confidence',
    'b36_context_memory',
    'b36_belief_lock',
    'b36_decision',
    'b36_genetic_generation',
    'b36_genetic_candidate',
    'b37_controller_profile',
    'b37_external_state_factor',
    'b37_internal_state_factor',
    'b37_factor_alignment',
    'b37_factor_confidence',
    'b37_factor_lock',
    'b37_decision',
    'b37_genetic_generation',
    'b37_genetic_candidate',
    'b38_controller_profile',
    'b38_external_attention',
    'b38_internal_attention',
    'b38_attention_balance',
    'b38_attention_gain',
    'b38_attention_lock',
    'b38_decision',
    'b38_genetic_generation',
    'b38_genetic_candidate',
    'b39_controller_profile',
    'b39_binding_strength',
    'b39_cross_factor_coherence',
    'b39_bound_context',
    'b39_binding_gain',
    'b39_binding_lock',
    'b39_decision',
    'b39_genetic_generation',
    'b39_genetic_candidate',
    'b40_controller_profile',
    'b40_workspace_activation',
    'b40_broadcast_gain',
    'b40_context_availability',
    'b40_workspace_stability',
    'b40_workspace_lock',
    'b40_decision',
    'b40_genetic_generation',
    'b40_genetic_candidate',
    'b41_controller_profile',
    'b41_executive_selection',
    'b41_inhibitory_pressure',
    'b41_goal_context',
    'b41_executive_stability',
    'b41_executive_lock',
    'b41_decision',
    'b41_genetic_generation',
    'b41_genetic_candidate',
    'b42_controller_profile',
    'b42_error_signal',
    'b42_conflict_signal',
    'b42_performance_context',
    'b42_monitor_stability',
    'b42_monitor_lock',
    'b42_decision',
    'b42_genetic_generation',
    'b42_genetic_candidate',
    'b43_controller_profile',
    'b43_precision_signal',
    'b43_adaptive_threshold',
    'b43_arousal_context',
    'b43_control_stability',
    'b43_precision_lock',
    'b43_decision',
    'b43_genetic_generation',
    'b43_genetic_candidate',
    'b44_controller_profile',
    'b44_relay_gate',
    'b44_sensory_precision',
    'b44_context_relay',
    'b44_gate_stability',
    'b44_relay_lock',
    'b44_decision',
    'b44_genetic_generation',
    'b44_genetic_candidate',
    'b45_controller_profile',
    'b45_inhibitory_gate',
    'b45_sensory_filter',
    'b45_context_suppression',
    'b45_loop_stability',
    'b45_inhibition_lock',
    'b45_decision',
    'b45_genetic_generation',
    'b45_genetic_candidate',
    'b46_controller_profile',
    'b46_feedback_gain',
    'b46_topdown_context',
    'b46_prediction_match',
    'b46_feedback_stability',
    'b46_feedback_lock',
    'b46_decision',
    'b46_genetic_generation',
    'b46_genetic_candidate',
    'b47_controller_profile',
    'b47_phase_alignment',
    'b47_synchrony_gain',
    'b47_cross_loop_coherence',
    'b47_phase_lock',
    'b47_decision',
    'b47_genetic_generation',
    'b47_genetic_candidate',
    'b48_controller_profile',
    'b48_timing_error',
    'b48_predictive_timing',
    'b48_corrective_gain',
    'b48_calibration_lock',
    'b48_decision',
    'b48_genetic_generation',
    'b48_genetic_candidate',
    'b49_controller_profile',
    'b49_go_signal',
    'b49_no_go_signal',
    'b49_action_gate_balance',
    'b49_selection_lock',
    'b49_decision',
    'b49_genetic_generation',
    'b49_genetic_candidate',
    'b50_controller_profile',
    'b50_habit_strength',
    'b50_chunk_value',
    'b50_habit_stability',
    'b50_chunk_lock',
    'b50_decision',
    'b50_genetic_generation',
    'b50_genetic_candidate',
    'b51_controller_profile',
    'b51_prediction_error',
    'b51_dopamine_gain',
    'b51_habit_modulation',
    'b51_modulation_lock',
    'b51_decision',
    'b51_genetic_generation',
    'b51_genetic_candidate',
    'b52_controller_profile',
    'b52_acetylcholine_level',
    'b52_precision_gain',
    'b52_uncertainty_signal',
    'b52_attention_lock',
    'b52_decision',
    'b52_genetic_generation',
    'b52_genetic_candidate',
    'b53_controller_profile',
    'b53_norepinephrine_level',
    'b53_arousal_gain',
    'b53_surprise_signal',
    'b53_gain_lock',
    'b53_decision',
    'b53_genetic_generation',
    'b53_genetic_candidate',
    'b54_controller_profile',
    'b54_serotonin_level',
    'b54_patience_signal',
    'b54_impulse_suppression',
    'b54_patience_lock',
    'b54_decision',
    'b54_genetic_generation',
    'b54_genetic_candidate',
    'b55_controller_profile',
    'b55_hypothalamic_drive',
    'b55_satiety_signal',
    'b55_recovery_bias',
    'b55_drive_balance',
    'b55_drive_lock',
    'b55_decision',
    'b55_genetic_generation',
    'b55_genetic_candidate',
    'b56_controller_profile',
    'b56_cortisol_level',
    'b56_stress_load',
    'b56_recovery_signal',
    'b56_endocrine_balance',
    'b56_stress_lock',
    'b56_decision',
    'b56_genetic_generation',
    'b56_genetic_candidate',
    'b57_controller_profile',
    'b57_interoceptive_awareness',
    'b57_visceral_salience',
    'b57_body_state_confidence',
    'b57_awareness_balance',
    'b57_awareness_lock',
    'b57_decision',
    'b57_genetic_generation',
    'b57_genetic_candidate',
    'b58_controller_profile',
    'b58_conflict_signal',
    'b58_error_likelihood',
    'b58_control_allocation',
    'b58_resolution_balance',
    'b58_conflict_lock',
    'b58_decision',
    'b58_genetic_generation',
    'b58_genetic_candidate',
    'b59_controller_profile',
    'b59_goal_context',
    'b59_working_set_stability',
    'b59_task_set_confidence',
    'b59_executive_balance',
    'b59_executive_lock',
    'b59_decision',
    'b59_genetic_generation',
    'b59_genetic_candidate',
    'b60_controller_profile',
    'b60_outcome_value',
    'b60_reversal_signal',
    'b60_goal_value_confidence',
    'b60_value_balance',
    'b60_value_lock',
    'b60_decision',
    'b60_genetic_generation',
    'b60_genetic_candidate',
    'b61_controller_profile',
    'b61_safety_value',
    'b61_threat_value',
    'b61_safety_confidence',
    'b61_affective_balance',
    'b61_safety_lock',
    'b61_decision',
    'b61_genetic_generation',
    'b61_genetic_candidate',
    'b62_controller_profile',
    'b62_defensive_mode',
    'b62_freeze_pressure',
    'b62_flee_pressure',
    'b62_shelter_bias',
    'b62_defense_balance',
    'b62_defense_lock',
    'b62_decision',
    'b62_genetic_generation',
    'b62_genetic_candidate',
)


class _BrainRuntimeActPayloadMixin:
    def _b_series_step_payload(
        self,
        direct_policy_trace_payload: Dict[str, object],
        semantic_logits: np.ndarray,
        semantic_policy: np.ndarray,
    ) -> dict[str, object]:
        if not self.config.is_b_series:
            payload = {name: None for name in _B_SERIES_STEP_PAYLOAD_FIELDS}
            payload.update(
                {
                    "b_level": -1,
                    "b_effective_level": None,
                    "b_mode": None,
                    "b_parent_level": None,
                    "b_transfer_source_checkpoint": None,
                    "b_transfer_coverage": None,
                    "semantic_action": None,
                    "semantic_action_idx": -1,
                    "learned_semantic_action": None,
                    "learned_semantic_action_idx": -1,
                    "semantic_action_source": None,
                    "semantic_action_reason": None,
                    "semantic_override_count": 0,
                    "semantic_logits": np.zeros(0, dtype=float),
                    "semantic_policy": np.zeros(0, dtype=float),
                    "bridge_primitive_action": None,
                    "bridge_reason": None,
                    "blocked_mask": {},
                    "food_delta_used": 0.0,
                    "shelter_delta_used": 0.0,
                }
            )
            return payload

        payload = {
            name: direct_policy_trace_payload.get(name)
            for name in _B_SERIES_STEP_PAYLOAD_FIELDS
        }
        payload.update(
            {
                "b_level": int(self.config.b_level),
                "b_effective_level": (
                    str(direct_policy_trace_payload.get("b_effective_level"))
                    if direct_policy_trace_payload.get("b_effective_level") is not None
                    else None
                ),
                "b_mode": str(self.config.b_mode),
                "b_parent_level": direct_policy_trace_payload.get("b_parent_level"),
                "b_transfer_source_checkpoint": direct_policy_trace_payload.get(
                    "b_transfer_source_checkpoint"
                ),
                "b_transfer_coverage": direct_policy_trace_payload.get(
                    "b_transfer_coverage"
                ),
                "semantic_action": direct_policy_trace_payload.get("semantic_action"),
                "semantic_action_idx": int(
                    direct_policy_trace_payload.get("semantic_action_idx", -1)
                ),
                "learned_semantic_action": direct_policy_trace_payload.get(
                    "learned_semantic_action"
                ),
                "learned_semantic_action_idx": int(
                    direct_policy_trace_payload.get("learned_semantic_action_idx", -1)
                ),
                "semantic_action_source": direct_policy_trace_payload.get(
                    "semantic_action_source"
                ),
                "semantic_action_reason": direct_policy_trace_payload.get(
                    "semantic_action_reason"
                ),
                "semantic_override_count": int(
                    direct_policy_trace_payload.get("semantic_override_count", 0)
                ),
                "semantic_logits": np.asarray(semantic_logits, dtype=float).copy(),
                "semantic_policy": np.asarray(semantic_policy, dtype=float).copy(),
                "bridge_primitive_action": direct_policy_trace_payload.get(
                    "bridge_primitive_action"
                ),
                "bridge_reason": direct_policy_trace_payload.get("bridge_reason"),
                "blocked_mask": dict(direct_policy_trace_payload.get("blocked_mask", {})),
                "food_delta_used": float(
                    direct_policy_trace_payload.get("food_delta_used", 0.0)
                ),
                "shelter_delta_used": float(
                    direct_policy_trace_payload.get("shelter_delta_used", 0.0)
                ),
            }
        )
        return payload
