"""Reward component names and profile configuration constants."""

from __future__ import annotations

from typing import Sequence

REWARD_COMPONENT_NAMES: Sequence[str] = (
    "action_cost",
    "terrain_cost",
    "night_exposure",
    "hunger_pressure",
    "fatigue_pressure",
    "sleep_debt_pressure",
    "predator_contact",
    "feeding",
    "resting",
    "food_progress",
    "shelter_progress",
    "predator_escape",
    "day_exploration",
    "shelter_entry",
    "night_shelter_bonus",
    "homeostasis_penalty",
    "death_penalty",
)

MINIMAL_SHAPING_SURVIVAL_THRESHOLD: float = 0.50

REWARD_PROFILES = {
    "classic": {
        "action_cost_stay": 0.008,
        "action_cost_move": 0.014,
        "base_hunger_cost": 0.010,
        "move_hunger_cost": 0.006,
        "idle_hunger_cost": 0.002,
        "base_fatigue_cost": 0.0035,
        "move_fatigue_cost": 0.003,
        "idle_fatigue_cost": 0.001,
        "turn_fatigue_cost": 0.002,
        "reverse_fatigue_cost": 0.004,
        "idle_open_penalty": 0.020,
        "clutter_fatigue": 0.002,
        "clutter_cost": 0.012,
        "narrow_fatigue": 0.0015,
        "narrow_cost": 0.010,
        "narrow_predator_risk": 0.035,
        "night_exposure_fatigue": 0.006,
        "night_exposure_debt": 0.009,
        "night_exposure_reward": 0.060,
        "hunger_pressure": 0.13,
        "fatigue_pressure": 0.08,
        "sleep_debt_pressure": 0.05,
        "food_progress": 0.30,
        "shelter_progress": 0.16,
        "threat_shelter_progress": 0.08,
        "predator_escape": 0.20,
        "predator_escape_bonus": 0.18,
        "predator_escape_stay_penalty": 0.08,
        "day_exploration_hungry": 0.05,
        "day_exploration_calm": 0.01,
        "shelter_entry": 0.10,
        "night_shelter_bonus": 0.08,
        "sleep_debt_night_awake": 0.007,
        "sleep_debt_day_awake": 0.0015,
        "sleep_debt_interrupt": 0.035,
        "sleep_debt_resting_night": 0.14,
        "sleep_debt_resting_day": 0.07,
        "sleep_debt_deep_night": 0.22,
        "sleep_debt_deep_day": 0.10,
        "sleep_debt_overdue_threshold": 0.72,
        "sleep_debt_health_penalty": 0.24,
        "recent_contact_decay": 0.35,
        "recent_pain_decay": 0.78,
        "death_penalty": 5.0,
    },
    "ecological": {
        "action_cost_stay": 0.010,
        "action_cost_move": 0.016,
        "base_hunger_cost": 0.010,
        "move_hunger_cost": 0.006,
        "idle_hunger_cost": 0.002,
        "base_fatigue_cost": 0.0035,
        "move_fatigue_cost": 0.003,
        "idle_fatigue_cost": 0.001,
        "turn_fatigue_cost": 0.002,
        "reverse_fatigue_cost": 0.004,
        "idle_open_penalty": 0.028,
        "clutter_fatigue": 0.003,
        "clutter_cost": 0.020,
        "narrow_fatigue": 0.0025,
        "narrow_cost": 0.015,
        "narrow_predator_risk": 0.060,
        "night_exposure_fatigue": 0.009,
        "night_exposure_debt": 0.014,
        "night_exposure_reward": 0.100,
        "hunger_pressure": 0.16,
        "fatigue_pressure": 0.10,
        "sleep_debt_pressure": 0.10,
        "food_progress": 0.04,
        "shelter_progress": 0.03,
        "threat_shelter_progress": 0.03,
        "predator_escape": 0.12,
        "predator_escape_bonus": 0.08,
        "predator_escape_stay_penalty": 0.12,
        "day_exploration_hungry": 0.01,
        "day_exploration_calm": 0.0,
        "shelter_entry": 0.02,
        "night_shelter_bonus": 0.0,
        "sleep_debt_night_awake": 0.011,
        "sleep_debt_day_awake": 0.002,
        "sleep_debt_interrupt": 0.050,
        "sleep_debt_resting_night": 0.18,
        "sleep_debt_resting_day": 0.08,
        "sleep_debt_deep_night": 0.28,
        "sleep_debt_deep_day": 0.12,
        "sleep_debt_overdue_threshold": 0.65,
        "sleep_debt_health_penalty": 0.34,
        "recent_contact_decay": 0.35,
        "recent_pain_decay": 0.78,
        "death_penalty": 5.0,
    },
    "austere": {
        "action_cost_stay": 0.010,
        "action_cost_move": 0.016,
        "base_hunger_cost": 0.010,
        "move_hunger_cost": 0.006,
        "idle_hunger_cost": 0.002,
        "base_fatigue_cost": 0.0035,
        "move_fatigue_cost": 0.003,
        "idle_fatigue_cost": 0.001,
        "turn_fatigue_cost": 0.002,
        "reverse_fatigue_cost": 0.004,
        "idle_open_penalty": 0.030,
        "clutter_fatigue": 0.003,
        "clutter_cost": 0.020,
        "narrow_fatigue": 0.0025,
        "narrow_cost": 0.016,
        "narrow_predator_risk": 0.065,
        "night_exposure_fatigue": 0.010,
        "night_exposure_debt": 0.015,
        "night_exposure_reward": 0.110,
        "hunger_pressure": 0.18,
        "fatigue_pressure": 0.11,
        "sleep_debt_pressure": 0.12,
        "food_progress": 0.0,
        "shelter_progress": 0.0,
        "threat_shelter_progress": 0.0,
        "predator_escape": 0.0,
        "predator_escape_bonus": 0.0,
        "predator_escape_stay_penalty": 0.0,
        "day_exploration_hungry": 0.0,
        "day_exploration_calm": 0.0,
        "shelter_entry": 0.0,
        "night_shelter_bonus": 0.0,
        "sleep_debt_night_awake": 0.012,
        "sleep_debt_day_awake": 0.0025,
        "sleep_debt_interrupt": 0.060,
        "sleep_debt_resting_night": 0.16,
        "sleep_debt_resting_day": 0.07,
        "sleep_debt_deep_night": 0.24,
        "sleep_debt_deep_day": 0.10,
        "sleep_debt_overdue_threshold": 0.60,
        "sleep_debt_health_penalty": 0.38,
        "recent_contact_decay": 0.35,
        "recent_pain_decay": 0.78,
        "death_penalty": 5.0,
    },
}


